version: "3"

volumes:
  db-data:

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      dev:
networks:
  dev:

